### PR TITLE
feat: Updates all dependencies, adjusts types and adds a `buildFrom` …

### PR DESCRIPTION
**Pull request by davelosert**
@sincovschi : I finally came around on providing a PR for issue #1 . It is not entirely finished yet as there are still some things left open I want to clarify with you before proceeding. As you can see I already adjusted quite some stuff, so let me give some proposals and background to it. Of course, feel free if you don't feel comfortable with those many changes or anything, no pressure here, it's just proposals. 🙂 

- **React Version 17**: The `providerFrom` wouldn't work with a lower version as 17 due to the types not being ready. So if we proceed, raising the version is a must. I also adjusted the `peerDependencie` to have `>=` rather than a caret to not be locked in to only the current version.
- **Remove carets in Versions**: I'd also propose not to use carets in the package.json anymore, as it prevents us from having predictable installations. For updates, I'd rather propose to incorporate [GitHub Dependabot ](https://github.com/dependabot/dependabot-core) in this repository.
- **Reduce ESLint Deps**: Right now, there are 9 ESLint-Plugins used for the little code we have. I wasn't even able to update it all to the newest version due to peer-dependency conflicts, which show that this is also kind of a maintenance hell 😅. Also, someof those rules are conflictin with each other. So my proposal here would be to ditch most of those plugins and only use the `@typescript-eslint` plugin for linting and maybe prettier.
- **Move Example Project to Stackblitz**: As nice as it is to have an exmaple project in the repository - maintaining that for such a small lilbrary is a burden as well. My proposal would be to move it to something like [Stackblitz](https://stackblitz.com/) and only link that in the documentation.
- **Move to GH Actions**: GitHub Actions would be a bit easier to maintain and everything would be in one plattform. So if you like, I could provide another PR to move the whole build and release to there. But that's not a must, if you are happy with travis it's okay.

### Some more minor things

- **Unused Dependencies**: I found some unused dependencies (`@testing-library/user-event`, `@types/node`, `eslint-plugin-promise`) that I went ahead and deleted.
- **Updated tsconfig.json**: Due to the update of `react-scripts`, some updates got automatically merged into the `tsconfig.json`.
- **Added Tests**: I also added some automated unit tests to ensure everything still works.

### CODE REVIEW

**Comment by sincovschi** [comment]
@davelosert, that's some serious work done.
I like a lot all the changes made.
But also I want to have a meeting with you as I proposed earlier.
I know that this is already a lot of your time,
but I want to make it right from the start and honor your contribution
because I lack the experience of open source development, I'm afraid I can break something.
Name a date if you are available and I'll try to sync.
Thanks.

**Comment by davelosert** [comment]
@sincovschi : Yes sure, lets set something up! From your profile I take that you are in UTC+2?
So how about tomorow at around 2 PM EET / 3 PM CET?

**Comment by sincovschi** [comment]
@davelosert, tomorrow at 2 PM EET / 3 PM CET, sounds great.

https://calendar.google.com/event?action=TEMPLATE&tmeid=Mm5zanY4aXV1Zm9tMHNycHJpZTVvZ3AybzUgMGdneS5zaW5AbQ&tmsrc=0ggy.sin%40gmail.com

Video call link: https://meet.google.com/xkr-rqab-iqs

**Comment by davelosert** [comment]
Great, thanks!
Looking forward to it!

**Pull request merged**
